### ISSUE TITLE
NoneType object is not an iterator

### ISSUE THREAD

**Issue by AshKumar06** [InitRoot/fransRecon#1] opened 2019-05-27 11:28 UTC
Fetching domain organisation for google.com using WHOIS.
- WHOIS lookup done, performing horizontal enumeration for {if found}: Google LLC

[*] Extracting from: https://viewdns.info/reversewhois/?q=Google+LLC

[!] Couldn't send query, error: {e} exiting...

Traceback (most recent call last):
  File "fransRecon.py", line 152, in <module>
    sys.exit(main(sys.argv[1]))
  File "fransRecon.py", line 147, in main
    horizontalEnum()
  File "fransRecon.py", line 116, in horizontalEnum
    next(scrapedData)
TypeError: NoneType object is not an iterator

**Comment by InitRoot** [comment] 2019-05-27 11:42
Hi,
Which python version are you using?

**Comment by AshKumar06** [comment] 2019-05-27 12:11
I am using python 2.7

**Comment by InitRoot** [comment] 2019-05-27 12:18
Might be that viewdns is catching you scraping. Did it work for other domains? Is this the only domain you've tried? Maybe PM me on twitter then we can debug properly. 

I will also run the same enumerating for company when I get home.

**Comment by InitRoot** [comment] 2019-05-27 16:27
I'm unable to reproduce your issue. 
You must be missing dependencies. Either on python or the bash side. Try to put some prints in to debug.
![Screenshot from 2019-05-27 18-26-35](https://user-images.githubusercontent.com/954507/58431216-14501180-80ad-11e9-963d-ed2df179ad0d.png)
Works flawless.

**Comment by InitRoot** [comment] 2019-05-27 16:28
Closing the issue as I cannot reproduce. Not a bug in the code.

**Closed as completed by InitRoot** 2019-05-27 16:28 UTC
Labels: bug

**Comment by AshKumar06** [comment] 2019-05-28 06:27
Ok  i will check the dependencies .

**Comment by InitRoot** [comment] 2019-05-28 08:00
Perfect, I've added the directory structure. 
Perhaps check that you replicate it fully.

**Comment by InitRoot** [comment] 2019-05-28 08:01
pip install pandas

The folder structure is as follow once installed:

 ✘ ⚡ root@pentest  ~/Tools/fransRecon  ls -la
total 96
drwxr-xr-x  4 root root  4096 May 27 18:29 .
drwxr-xr-x 14 root root  4096 May 26 12:48 ..
-rwxr--r--  1 root root  5545 May 26 22:17 fransRecon.py
drwxr-xr-x  2 root root  4096 May 26 21:00 subbrute
drwxr-xr-x  3 root root  4096 May 26 21:00 Sublist3r
-rwxr-xr-x  1 root root 36120 May 26 21:00 sublist3r.py
-rw-r--r--  1 root root 36642 May 26 21:00 sublist3r.pyc

**Comment by sachincool** [comment] 2019-08-11 20:43
![image](https://user-images.githubusercontent.com/25671488/62839341-84caff80-bca6-11e9-87f8-7472fb8629af.png)

Having a similar issue, 
Python v2.7.15+
I have all the dependencies.
